package kbs

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"gopkg.in/yaml.v3"

	"github.com/confidential-devhub/cococtl/pkg/k8s"
	"github.com/confidential-devhub/cococtl/pkg/kbsclient"
	"github.com/confidential-devhub/cococtl/pkg/sealed"
	"github.com/confidential-devhub/cococtl/pkg/secrets"
	"github.com/confidential-devhub/cococtl/pkg/trustee"
)

var populateCmd = &cobra.Command{
	Use:   "populate",
	Short: "Upload resources to a KBS instance",
	Long: `Upload resources to a Key Broker Service (KBS) instance via the KBS admin HTTP API.

Input modes (mutually exclusive):
  -f <yaml>                              Load resources from a trustee secrets YAML file
                                         (generated by 'kubectl coco apply')
  --path <kbs-path> --resource-file <f>  Upload a single file to the specified KBS path
  --from-k8s-secret <name>              Fetch a Kubernetes Secret and upload each key

KBS connection:
  --kbs-url    Direct KBS URL (skips port-forward; for external KBS)
  (default)    Port-forward to the in-cluster KBS pod (requires --namespace or current context)

Authentication (resolution order: --auth-key > --auth-dir > config > default dir):
  --auth-key   Path to the Ed25519 private key PEM file
  --auth-dir   Directory containing private.key (default: ~/.kube/coco-kbs-auth)
  --tls-ca     Optional PEM-encoded CA certificate for HTTPS KBS URLs

Examples:
  kubectl coco kbs populate -f app-trustee-secrets.yaml
  kubectl coco kbs populate --path default/myapp/password --resource-file /path/to/password.txt
  kubectl coco kbs populate --from-k8s-secret my-registry-secret -n my-namespace
  kubectl coco kbs populate --kbs-url http://kbs.example.com:8080 --auth-key /path/to/private.key -f secrets.yaml`,
	RunE: runPopulate,
}

var (
	populateFilename      string
	populateKBSPath       string
	populateResourceFile  string
	populateFromK8sSecretName string
	populateKBSURL        string
	populateAuthDir       string
	populateAuthKey       string
	populateTLSCA         string
	populateNamespace     string
)

func init() {
	populateCmd.Flags().StringVarP(&populateFilename, "filename", "f", "", "Path to trustee secrets YAML file (generated by 'kubectl coco apply')")
	populateCmd.Flags().StringVar(&populateKBSPath, "path", "", "KBS resource path in 'repository/type/tag' format (use with --resource-file)")
	populateCmd.Flags().StringVar(&populateResourceFile, "resource-file", "", "File whose contents are uploaded to --path")
	populateCmd.Flags().StringVar(&populateFromK8sSecretName, "from-k8s-secret", "", "Kubernetes Secret name to fetch and upload (all keys)")
	populateCmd.Flags().StringVar(&populateKBSURL, "kbs-url", "", "Direct KBS URL (e.g. http://localhost:8080); skips port-forward")
	populateCmd.Flags().StringVar(&populateAuthDir, "auth-dir", "", "Directory containing private.key (default: ~/.kube/coco-kbs-auth)")
	populateCmd.Flags().StringVar(&populateAuthKey, "auth-key", "", "Path to Ed25519 private key PEM file")
	populateCmd.Flags().StringVar(&populateTLSCA, "tls-ca", "", "PEM-encoded CA certificate for TLS verification")
	populateCmd.Flags().StringVarP(&populateNamespace, "namespace", "n", "", "Kubernetes namespace (for in-cluster KBS pod lookup and secret lookup)")
}

func runPopulate(cmd *cobra.Command, _ []string) error {
	ctx := cmd.Context()

	// Validate input mode
	inputMode, err := resolveInputMode()
	if err != nil {
		return err
	}

	// Create KBS client
	kbsClient, stopForward, err := createPopulateKBSClient(ctx)
	if err != nil {
		return err
	}
	defer stopForward()

	switch inputMode {
	case "file":
		return populateFromFile(ctx, kbsClient, populateFilename)
	case "path":
		return populateFromResourceFile(ctx, kbsClient, populateKBSPath, populateResourceFile)
	case "k8s-secret":
		return uploadFromK8sSecret(ctx, kbsClient, populateFromK8sSecretName, populateNamespace)
	default:
		return fmt.Errorf("internal error: unknown input mode %q", inputMode)
	}
}

// resolveInputMode validates flags and returns the active input mode.
func resolveInputMode() (string, error) {
	modes := 0
	mode := ""

	if populateFilename != "" {
		modes++
		mode = "file"
	}
	if populateKBSPath != "" || populateResourceFile != "" {
		modes++
		mode = "path"
	}
	if populateFromK8sSecretName != "" {
		modes++
		mode = "k8s-secret"
	}

	if modes == 0 {
		return "", fmt.Errorf("one of -f, --path/--resource-file, or --from-k8s-secret is required")
	}
	if modes > 1 {
		return "", fmt.Errorf("-f, --path/--resource-file, and --from-k8s-secret are mutually exclusive")
	}

	if mode == "path" {
		if populateKBSPath == "" {
			return "", fmt.Errorf("--path is required when --resource-file is specified")
		}
		if populateResourceFile == "" {
			return "", fmt.Errorf("--resource-file is required when --path is specified")
		}
	}

	return mode, nil
}

// createPopulateKBSClient builds a kbsclient.Client using flag-based auth resolution
// (explicit --auth-key > --auth-dir > config KBSAuthDir > default dir).
// If --kbs-url is provided the client connects directly; otherwise a port-forward is set up.
// The caller must invoke the returned stop function when done.
func createPopulateKBSClient(ctx context.Context) (*kbsclient.Client, func(), error) {
	noop := func() {}

	// Optional TLS CA (relevant only for direct-URL mode with HTTPS endpoints).
	var caCert []byte
	if populateTLSCA != "" {
		var err error
		// #nosec G304 -- path provided by the user via flag
		caCert, err = os.ReadFile(populateTLSCA)
		if err != nil {
			return nil, noop, fmt.Errorf("failed to read TLS CA from %s: %w", populateTLSCA, err)
		}
	}

	// Direct URL mode: load key and connect directly to the provided URL.
	if populateKBSURL != "" {
		pemData, err := loadPrivateKeyPEM(populateAuthKey, populateAuthDir)
		if err != nil {
			return nil, noop, err
		}
		client, err := kbsclient.NewFromPEM(populateKBSURL, pemData, caCert)
		if err != nil {
			return nil, noop, fmt.Errorf("failed to create KBS client: %w", err)
		}
		return client, noop, nil
	}

	// Port-forward mode: determine the namespace where KBS is deployed.
	kbsNamespace, err := resolveKBSNamespace()
	if err != nil {
		return nil, noop, err
	}

	k8sClient, err := k8s.NewClient(k8s.ClientOptions{})
	if err != nil {
		return nil, noop, fmt.Errorf("failed to create Kubernetes client: %w", err)
	}

	if populateAuthKey != "" {
		// --auth-key explicitly provided: load from that file and use it for the connection
		// so the flag is honoured rather than silently falling back to the auth directory.
		pemData, err := loadPrivateKeyPEM(populateAuthKey, "")
		if err != nil {
			return nil, noop, err
		}
		client, stop, err := trustee.NewClientWithPortForwardFromPEM(ctx, k8sClient.Config, k8sClient.Clientset, kbsNamespace, pemData)
		if err != nil {
			return nil, noop, fmt.Errorf("failed to connect to KBS via port-forward (namespace: %s): %w", kbsNamespace, err)
		}
		return client, stop, nil
	}

	// No --auth-key: resolve auth dir from --auth-dir, config, or the default location.
	authDir, err := resolveAuthDir(populateAuthDir)
	if err != nil {
		return nil, noop, err
	}
	client, stop, err := trustee.NewClientWithPortForward(ctx, k8sClient.Config, k8sClient.Clientset, kbsNamespace, authDir)
	if err != nil {
		return nil, noop, fmt.Errorf("failed to connect to KBS via port-forward (namespace: %s): %w", kbsNamespace, err)
	}
	return client, stop, nil
}

// loadPrivateKeyPEM returns the PEM bytes for the Ed25519 private key.
// Resolution order: explicit file (authKey) > directory (authDir) > config KBSAuthDir > default dir.
func loadPrivateKeyPEM(authKey, authDir string) ([]byte, error) {
	if authKey != "" {
		// #nosec G304 -- path provided by the user via flag
		data, err := os.ReadFile(authKey)
		if err != nil {
			return nil, fmt.Errorf("failed to read private key from %s: %w", authKey, err)
		}
		return data, nil
	}

	resolvedDir, err := resolveAuthDir(authDir)
	if err != nil {
		return nil, err
	}

	keyPath := filepath.Join(resolvedDir, "private.key")
	// #nosec G304 -- path is derived from trustee.DefaultAuthDir, an application-controlled location
	data, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read KBS private key from %s (run 'kubectl coco init' first): %w", keyPath, err)
	}
	return data, nil
}

// resolveAuthDir returns the auth directory to use.
// Resolution order: explicit flag (--auth-dir) → config KBSAuthDir → default dir (~/.kube/coco-kbs-auth).
func resolveAuthDir(authDirFlag string) (string, error) {
	if authDirFlag != "" {
		return trustee.DefaultAuthDir(authDirFlag)
	}

	// Try config
	if cfg, err := loadCocoConfig(); err == nil && cfg.KBSAuthDir != "" {
		return trustee.DefaultAuthDir(cfg.KBSAuthDir)
	}

	// Default dir
	return trustee.DefaultAuthDir("")
}

// resolveKBSNamespace returns the namespace where the KBS pod is deployed.
// Priority: --namespace flag > config TrusteeServer-derived namespace > current context namespace.
func resolveKBSNamespace() (string, error) {
	if populateNamespace != "" {
		return populateNamespace, nil
	}

	// Try to derive from config's TrusteeServer URL.
	// Only skip when GetTrusteeNamespace returns empty (parse failure), not when it
	// legitimately returns "default" — KBS may be deployed in the default namespace.
	if cfg, err := loadCocoConfig(); err == nil && cfg.TrusteeServer != "" {
		if ns := cfg.GetTrusteeNamespace(); ns != "" {
			return ns, nil
		}
	}

	// Fall back to current context namespace
	ns, err := k8s.GetCurrentNamespace()
	if err != nil {
		return "", fmt.Errorf("failed to determine KBS namespace: %w (use --namespace to specify)", err)
	}
	return ns, nil
}

// populateFromFile reads a trustee secrets YAML (generated by 'kubectl coco apply'), fetches the
// corresponding Kubernetes Secrets, and uploads each key's value to KBS.
func populateFromFile(ctx context.Context, kbsClient *kbsclient.Client, filename string) error {
	// #nosec G304 -- path provided by the user via flag
	data, err := os.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("failed to read trustee secrets file %s: %w", filename, err)
	}

	var cfg secrets.TrusteeConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return fmt.Errorf("failed to parse trustee secrets file %s: %w", filename, err)
	}

	if len(cfg.Secrets) == 0 {
		fmt.Println("No secrets found in trustee secrets file")
		return nil
	}

	// Create K8s client for secret lookup
	k8sClient, err := k8s.NewClient(k8s.ClientOptions{})
	if err != nil {
		return fmt.Errorf("failed to create Kubernetes client for secret lookup: %w", err)
	}

	fmt.Printf("Uploading %d resource(s) to KBS...\n", len(cfg.Secrets))

	for _, entry := range cfg.Secrets {
		if err := populateOneFromTrusteeEntry(ctx, kbsClient, k8sClient, entry); err != nil {
			return err
		}
	}

	fmt.Println("All resources uploaded successfully")
	return nil
}

// populateOneFromTrusteeEntry uploads a single trustee secrets YAML entry to KBS.
// It parses the KBS URI to find the originating K8s secret name/namespace/key, fetches
// the secret from the cluster, and uploads the raw bytes to KBS.
func populateOneFromTrusteeEntry(ctx context.Context, kbsClient *kbsclient.Client, k8sClient *k8s.Client, entry secrets.TrusteeSecretEntry) error {
	// Parse the KBS URI: kbs:///namespace/secretname/kbskey
	ns, secretName, kbsKey, err := sealed.ParseResourceURI(entry.ResourceURI)
	if err != nil {
		return fmt.Errorf("invalid resource URI %q: %w", entry.ResourceURI, err)
	}

	// Fetch the original K8s secret to get the raw value to upload.
	// The trustee secrets YAML records the KBS URI but not the actual bytes —
	// those still live in the K8s secret that existed when 'kubectl coco apply' ran.
	k8sSecret, err := k8sClient.Clientset.CoreV1().Secrets(ns).Get(ctx, secretName, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf(
			"failed to fetch K8s secret %s/%s: %w\n\n"+
				"The -f mode requires the original K8s secret to exist in the cluster.\n"+
				"Alternatives:\n"+
				"  kubectl coco kbs populate --from-k8s-secret %s -n %s\n"+
				"  kubectl coco kbs populate --path %s/%s/%s --resource-file <file>",
			ns, secretName, err, secretName, ns, ns, secretName, kbsKey)
	}

	// Find the key in the secret: try the kbsKey directly, then with a leading dot
	// (leading dots are stripped from KBS keys since KBS URIs don't support them).
	value, ok := k8sSecret.Data[kbsKey]
	if !ok {
		value, ok = k8sSecret.Data["."+kbsKey]
	}
	if !ok {
		return fmt.Errorf("key %q not found in K8s secret %s/%s (available keys: %s)",
			kbsKey, ns, secretName, joinKeys(k8sSecret.Data))
	}

	// Build KBS path from URI components (strip the kbs:/// prefix)
	kbsPath := ns + "/" + secretName + "/" + kbsKey

	fmt.Printf("  Uploading %s -> kbs:///%s\n", entry.ResourceURI, kbsPath)
	if err := kbsClient.SetResource(ctx, kbsPath, value); err != nil {
		return fmt.Errorf("failed to upload %s to KBS: %w", kbsPath, err)
	}
	return nil
}

// populateFromResourceFile uploads the content of a local file to a specific KBS path.
func populateFromResourceFile(ctx context.Context, kbsClient *kbsclient.Client, kbsPath, resourceFile string) error {
	// #nosec G304 -- path provided by the user via flag
	data, err := os.ReadFile(resourceFile)
	if err != nil {
		return fmt.Errorf("failed to read resource file %s: %w", resourceFile, err)
	}

	fmt.Printf("Uploading %s to kbs:///%s...\n", resourceFile, kbsPath)
	if err := kbsClient.SetResource(ctx, kbsPath, data); err != nil {
		return fmt.Errorf("failed to upload to KBS path %s: %w", kbsPath, err)
	}

	fmt.Printf("Uploaded successfully to kbs:///%s\n", kbsPath)
	return nil
}

// uploadFromK8sSecret fetches all keys from a Kubernetes Secret and uploads each to KBS.
// The KBS path for each key is: <namespace>/<secretName>/<cleanKey>.
// For image pull secrets, the .dockercfg format is converted to .dockerconfigjson before upload.
func uploadFromK8sSecret(ctx context.Context, kbsClient *kbsclient.Client, secretName, namespace string) error {
	// Resolve namespace
	ns := namespace
	if ns == "" {
		var err error
		ns, err = k8s.GetCurrentNamespace()
		if err != nil {
			return fmt.Errorf("failed to get current namespace: %w", err)
		}
	}

	k8sClient, err := k8s.NewClient(k8s.ClientOptions{})
	if err != nil {
		return fmt.Errorf("failed to create Kubernetes client: %w", err)
	}

	k8sSecret, err := k8sClient.Clientset.CoreV1().Secrets(ns).Get(ctx, secretName, metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("failed to fetch K8s secret %s/%s: %w", ns, secretName, err)
	}

	if len(k8sSecret.Data) == 0 {
		fmt.Printf("K8s secret %s/%s has no data keys\n", ns, secretName)
		return nil
	}

	fmt.Printf("Uploading %d key(s) from K8s secret %s/%s to KBS...\n", len(k8sSecret.Data), ns, secretName)

	for key, value := range k8sSecret.Data {
		// Apply the same key normalization used during 'apply':
		// - .dockercfg keys get converted to .dockerconfigjson format
		// - leading dots are stripped for KBS URI compatibility
		kbsKey := trustee.GetKBSKeyName(key)

		// Handle .dockercfg -> .dockerconfigjson data conversion
		if key == ".dockercfg" {
			converted, err := trustee.ConvertDockercfgToDockerConfigJSON(value)
			if err != nil {
				return fmt.Errorf("failed to convert .dockercfg to .dockerconfigjson for secret %s/%s: %w", ns, secretName, err)
			}
			value = converted
		}

		kbsPath := ns + "/" + secretName + "/" + kbsKey
		fmt.Printf("  Uploading key %q -> kbs:///%s\n", key, kbsPath)
		if err := kbsClient.SetResource(ctx, kbsPath, value); err != nil {
			return fmt.Errorf("failed to upload key %q from secret %s/%s to KBS: %w", key, ns, secretName, err)
		}
	}

	fmt.Println("All keys uploaded successfully")
	return nil
}

// joinKeys returns a comma-separated list of keys from a map for error messages.
func joinKeys(data map[string][]byte) string {
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	return strings.Join(keys, ", ")
}
